// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_sensornameTemp;
lv_obj_t *ui_Temperature;
void ui_event_Templabel( lv_event_t * e);
lv_obj_t *ui_Templabel;
void ui_event_namelabel( lv_event_t * e);
lv_obj_t *ui_namelabel;
void ui_event_Time( lv_event_t * e);
lv_obj_t *ui_Time;
void ui_event_Day( lv_event_t * e);
lv_obj_t *ui_Day;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Screen1, &ui_img_background_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_sensornameTemp = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_sensornameTemp, 117);
lv_obj_set_height( ui_sensornameTemp, 80);
lv_obj_set_x( ui_sensornameTemp, -167 );
lv_obj_set_y( ui_sensornameTemp, -130 );
lv_obj_set_align( ui_sensornameTemp, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_sensornameTemp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_sensornameTemp, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_sensornameTemp, lv_color_hex(0x8F7070), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sensornameTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_opa(ui_sensornameTemp, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor(ui_sensornameTemp, lv_color_hex(0x9A3B3B), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_sensornameTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_sensornameTemp, lv_color_hex(0x7B5D5D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_sensornameTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Temperature = lv_obj_create(ui_sensornameTemp);
lv_obj_set_width( ui_Temperature, 100);
lv_obj_set_height( ui_Temperature, 50);
lv_obj_set_x( ui_Temperature, 0 );
lv_obj_set_y( ui_Temperature, 13 );
lv_obj_set_align( ui_Temperature, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Temperature, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Temperature, lv_color_hex(0x9F1A1A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Temperature, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_grad_color(ui_Temperature, lv_color_hex(0x781616), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_Temperature, lv_color_hex(0x711818), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Temperature, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Temperature, lv_color_hex(0x8A4848), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Temperature, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Templabel = lv_label_create(ui_Temperature);
lv_obj_set_width( ui_Templabel, 60);
lv_obj_set_height( ui_Templabel, 19);
lv_obj_set_x( ui_Templabel, -1 );
lv_obj_set_y( ui_Templabel, 0 );
lv_obj_set_align( ui_Templabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_Templabel,"--:--");
lv_obj_set_style_text_align(ui_Templabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_namelabel = lv_label_create(ui_sensornameTemp);
lv_obj_set_width( ui_namelabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_namelabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_namelabel, -1 );
lv_obj_set_y( ui_namelabel, -23 );
lv_obj_set_align( ui_namelabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_namelabel,"sensorname");

ui_Time = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Time, -219 );
lv_obj_set_y( ui_Time, -228 );
lv_obj_set_align( ui_Time, LV_ALIGN_CENTER );
lv_label_set_text(ui_Time,"--:--");
lv_obj_set_style_text_color(ui_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Day = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Day, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Day, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Day, 200 );
lv_obj_set_y( ui_Day, -227 );
lv_obj_set_align( ui_Day, LV_ALIGN_CENTER );
lv_label_set_text(ui_Day,"DD/MN/2023");
lv_obj_set_style_text_color(ui_Day, lv_color_hex(0xF6DBDB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Day, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Templabel, ui_event_Templabel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_namelabel, ui_event_namelabel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Time, ui_event_Time, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Day, ui_event_Day, LV_EVENT_ALL, NULL);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Templabel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_REFRESH) {
      value( e );
}
}
void ui_event_namelabel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_REFRESH) {
      ( e );
}
}
void ui_event_Time( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_REFRESH) {
      ( e );
}
}
void ui_event_Day( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_REFRESH) {
      ( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
