
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_sensornameTemp;
extern lv_obj_t *ui_Temperature;
void ui_event_Templabel( lv_event_t * e);
extern lv_obj_t *ui_Templabel;
void ui_event_namelabel( lv_event_t * e);
extern lv_obj_t *ui_namelabel;
void ui_event_Time( lv_event_t * e);
extern lv_obj_t *ui_Time;
void ui_event_Day( lv_event_t * e);
extern lv_obj_t *ui_Day;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_background_png);   // assets\red-abstract-roundabout-modern480Yeer.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
